name: Monitor Website ITS

on:
  schedule:
    - cron: "*/15 * * * *"  # setiap 15 menit
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Jalankan monitoring
        run: python scripts/monitor.py

      - name: Commit hasil pengujian ke repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add hasil_pengujian.csv
          git commit -m "Update hasil pengujian $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
